---

# Tune server to improve performance for database 
- include: tune_performance.yml

- name: Check if MongoDB is already installed
  stat:
    path: /etc/mongod.conf
  register: mongodb_installed

- name: Import MongoDB public GPG Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E162F504A20CDF15827F718D4B7C549A058F8B6B
    state: present

- name: Add MongoDB official APT repository
  apt_repository:
    repo: "{{ mongodb_apt_repository }}"
    state: present
    filename: mongodb-org-{{ mongodb_version }}
    update_cache: yes

# By default, MongoDB would not be started and enabled after installation on
# Ubuntu. So we don't need to stop MongoDB manually, but do need to manually
# reload systemd daemon to load the MongoDB systemd unit before enable/start it.
- name: Ensure MongoDB is installed
  package: name=mongodb-org state=present

- name: Ensure MongoDB is configured
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongodb

- name: Create db path if it does not exist
  file:
    path: "{{ mongodb_db_path }}"
    state: directory
    owner: mongodb
    group: mongodb
    mode: 0755

- name: Reload systemd daemon to load initial installed MongoDB systemd unit
  systemd: name={{ mongodb_daemon }} daemon_reload=yes
  when: not mongodb_installed.stat.exists

- name: Ensure MongoDB is running and enabled on boot
  service: name={{ mongodb_daemon }} state=started enabled=yes
